version: '2'

services:
  opensearch:
    container_name: magento2opensearch
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "plugins.security.disabled=true"
    build: opensearchproject/opensearch:1.2.4
    ports:
      - "9200:9200"
networks:
  default:
    external:
      name: env_default
